Include Codiva.io in the list of compilers
arnemertz/online-compilers pull request #11
Opened 2018-01-02 03:33 UTC by jayaprabhakar

Codiva online compiler and IDE supports C, C++ and Java. 

It has syntax highlighting, continuous compilation, and works on mobile.

2018-01-08 05:22 UTC, arnemertz requested changes
Thanks for the PR! The Clang version is 3.5, and you changed the alternate text for the badge, but not the badge itself, it is still Clang-4.0-008080.svg
Could you change it to Clang-3.5?

You also note the compilation every few keystrokes. I could not verify it, i.e. it does compile only if I hit "run" (not logged in). Can you describe how to activate the feature?

2018-01-10 05:33 UTC, jayaprabhakar commented
How do I find the badge image for the clang-3.5 version?

You may have to click 'Edit' to start editing. For other's project it always starts in readonly mode.

1. Try this project [https://www.codiva.io/p/0a5bebbd-210b-412e-aa5f-e4b029fa08c8](https://www.codiva.io/p/0a5bebbd-210b-412e-aa5f-e4b029fa08c8)
1. Click **Edit**
1. You will see 2 compilation errors.
1. Try fixing the errors.
    1. Insert the ';'
    1. correctly define the variable 'c'

2018-01-11 13:19 UTC, arnemertz commented on index.md
> +![Clang 3.5](https://img.shields.io/badge/Clang-4.0-008080.svg)
use `![Clang 3.5](https://img.shields.io/badge/Clang-3.5-008080.svg)` instead

2018-01-11 13:24 UTC, arnemertz commented
The badge images are created from their URL, i.e. use another name and the image is different. You copied the use of `https://img.shields.io/badge/Clang-4.0-008080.svg` which is the Clang 4.0 badge, use `https://img.shields.io/badge/Clang-3.5-008080.svg` instead to make it a Clang 3.5 badge. More details here under "Your Badge" almost at the end of the page: https://shields.io/

2018-01-13 20:29 UTC, merged

2018-01-13 20:30 UTC, arnemertz commented
Thanks @jayaprabhakar!

2018-01-13 21:39 UTC, jayaprabhakar commented
Thanks @arnemertz. 
I see that you maintain another site https://arne-mertz.de/2017/05/online-compilers/ 
Would you mind including Codiva in that list?

2018-01-13 21:46 UTC, arnemertz commented
That other one is a post that isn't maintained and explicitly points to this site.